CHANNELS = [
    {"id": "UCpzdPGGdUd0zTDPq9iMPGgg", "label": "Sra Nina"},
    {"id": "UCQgBAOB2rDFR0QN2IYASEPg", "label": "Hajime D. Kaminari"},
    {"id": "UC23jqhzGWaKBriRQSTTvL4Q", "label": "tia yuh"},
    {"id": "UCTYhND1pyDHK8_WESBflINw", "label": "Mr. Luffy"},
    {"id": "UCCBkan73f07cpQiU7NtMJ2A", "label": "Mr. Enel"},
    {"id": "UCOL3UrCuyPGoGH3jYqJXH2g", "label": "LuciTtor"},
    {"id": "UCdvGosrHkxIyyx9f0Zjb3wQ", "label": "Quaso"},
    {"id": "UC_0KnTorOqFGtAY3dNtuiEQ", "label": "Creudo"},
    {"id": "UCtCnPIMHPUnyN6UWe8uLO4g", "label": "Light GC"},
    {"id": "UCL1vHJDdPrMBwbHtMPII3vw", "label": "Hariik"},
    {"id": "UCKzu9MDO0irvwgF2vdTATIA", "label": "Daiki zz"},
    {"id": "UCJtnbMRP9iDgvJeu1Wevb_w", "label": "JOHAN-SAMA"},
    {"id": "UCr64Iy6JiBJv-w1E5A5R2eQ", "label": "AML Studios"},
    {"id": "UCyf03vt3z8A3SYQg4F9vMpg", "label": "Taegao"},
    {"id": "UCz9SqRu1_fhE7cYtDKSQTSg", "label": "Sra Asuka"},
    {"id": "UCzS69DRMmbrW6khTEhNJDUQ", "label": "Michikatsu Tsugikuni"},
    {"id": "UCpLKNt1lOwFW4RKi-SPnJJw", "label": "Accel Leywin"},
    {"id": "UCeMVeRWvKqqSIsh8GDqWW3w", "label": "Eclipse Moon"},
    {"id": "UCFJmIvhqVj6fIlhgnOXgTsw", "label": "Taia"},
    {"id": "UCXTf02tzzgfiBcfJPQNFspA", "label": "GojoOficial"},
    {"id": "UC0QsoVWnV0V9VCID55x3v2Q", "label": "The Dottore"},
    {"id": "UC6PIuVnfWcEEf6fDOtd34SQ", "label": "🐪🌵ミカさん"},
    {"id": "UCv50uLMsqcfd2voCcGS3HBA", "label": "Sr uchiha"},
    {"id": "UCPjOOc5T-FFNl9B7cdrAimQ", "label": "kiri_sama"},
    {"id": "UCsQTckKPDpFeCGbkHKlJrog", "label": "Urahara Sans💀"},
    {"id": "UCclLlqIxzUWe1lB2ARpEDrw", "label": "AZUL4"},
    {"id": "UCbOg8MThhEuhSLT6Ylg079g", "label": "Zenki"},
    {"id": "UCmeheNLE3hkAzgWTNpZcDSQ", "label": "𝓢𝓻.𝓕𝓪𝓬𝓮月"},
    {"id": "UCJSma7cB4so7Ti67KlWt5KA", "label": "it's potato"},
    {"id": "UC6E3uzvspZiWM96JhYjEr3Q", "label": "Raizo"},
    {"id": "UCIXxAsITvEuv-zGQRpN6zUw", "label": "♥️ĐƗØǤØ♠️"},
]